Node: mriqc_wf.anatMRIQC.synthstrip_wf.synthstrip
Working directory: /home/mollyi/Projects/EMRIqc/code/mriqc-flair/mriqc/work/mriqc_wf/anatMRIQC/synthstrip_wf/ecfd47363e3d5e65df7d2623800afe83eae6204b/synthstrip

Node inputs:

args = <undefined>
border_mm = 1
environ = {}
in_file = /home/mollyi/Projects/EMRIqc/code/mriqc-flair/mriqc/work/mriqc_wf/anatMRIQC/synthstrip_wf/ecfd47363e3d5e65df7d2623800afe83eae6204b/pre_n4/clipped_corrected.nii.gz
model = <undefined>
num_threads = 14
out_file = <undefined>
out_mask = <undefined>
use_gpu = False

Traceback (most recent call last):
  File "/home/mollyi/Projects/EMRIqc/code/mriqc-flair/mriqc/mriqc/engine/plugin.py", line 64, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home/mollyi/Projects/.virtualenvs/emriqc_mriqc24-0-02/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 525, in run
    result = self._run_interface(execute=True)
  File "/home/mollyi/Projects/.virtualenvs/emriqc_mriqc24-0-02/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_interface
    return self._run_command(execute)
  File "/home/mollyi/Projects/.virtualenvs/emriqc_mriqc24-0-02/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 769, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node synthstrip.

Cmdline:
	synthstrip -b 1 -i /home/mollyi/Projects/EMRIqc/code/mriqc-flair/mriqc/work/mriqc_wf/anatMRIQC/synthstrip_wf/ecfd47363e3d5e65df7d2623800afe83eae6204b/pre_n4/clipped_corrected.nii.gz -n 14 -o clipped_corrected_desc-brain.nii.gz -m clipped_corrected_desc-brain_mask.nii.gz
Stdout:
	Configuring model on the CPU
Stderr:
	Traceback (most recent call last):
	  File "/home/mollyi/Projects/.virtualenvs/emriqc_mriqc24-0-02/bin/synthstrip", line 8, in <module>
	    sys.exit(main())
	  File "/home/mollyi/Projects/.virtualenvs/emriqc_mriqc24-0-02/lib/python3.10/site-packages/mriqc/synthstrip/cli.py", line 117, in main
	    raise RuntimeError('A model must be provided.')
	RuntimeError: A model must be provided.
Traceback:
	RuntimeError: subprocess exited with code 1.
